// <auto-generated />
namespace Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class idx_parkDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(idx_parkDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201501181714565_idx_parkDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
